# configuration for "master" branch
# build in Debug mode and Test

-
  branches:
    only:
    - master

  image: Visual Studio 2017

  environment:
    release_version: '0.9.7'

  version: $(release_version).{build}

  configuration: Debug

  build:
    project: Liquid.NET.sln
    publish_nuget: true
    include_nuget_references: true

  before_build:
  - nuget restore

  test_script:
  - .\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:"packages\xunit.runner.console.2.2.0\tools\xunit.console.x86.exe" -targetargs:""".\Liquid.NET.Tests\bin\Debug\Liquid.NET.Tests.dll"" /noshadow" -excludebyattribute:*.ExcludeFromCodeCoverage* -filter:"+[Liquid.NET]* -[Liquid.NET]Liquid.NET.Tests.*" -returntargetcode -output:.\Liquid.NET.coverage.xml
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "Liquid.NET.coverage.xml"

  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}-dev'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'

  nuget:
    project_feed: true

# configuration for "release" branch
# build in Debug mode and Test

-
  branches:
    only:
    - release

  image: Visual Studio 2017

  environment:
    release_version: '0.9.7'

  version: $(release_version).{build}
  configuration: Release
  before_build:
    - nuget restore

  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '$(release_version)'
    assembly_file_version: '$(release_version)'
    assembly_informational_version: '$(release_version)'
  nuget:
    account_feed: true
    project_feed: true
  build:
    project: Liquid.NET.sln
    publish_nuget: true
    include_nuget_references: true
    verbosity: minimal
  deploy:
  - provider: NuGet
    prerelease: false
    api_key:
      secure:  VupoidE3HdOx3mLhAdrOX/liMBaU122WL+0etvpc1fmlw6/8lE6W3TcLwByCFzhx
      artifact: /.*\.nupkg/
#    on:
#      appveyor_repo_tag: true